library(data.table)
t<-read.table("household_power_consumption.txt", header = TRUE, sep = ";", dec = ".")
tb<-t
tb$Date<-as.Date(tb$Date,"%d/%m/%Y")
dt<-data.table(tb)
DT<-dt[dt$Date>="2007-02-01" & dt$Date<="2007-02-02",]
x<-paste(DT$Date,DT$Time)
x<-as.character(x)
x<-strptime(x, format = "%Y-%m-%d %H:%M:%S", tz="GMT")
DT$Sub_metering_1<-as.numeric(as.character(DT$Sub_metering_1))
DT$Sub_metering_2<-as.numeric(as.character(DT$Sub_metering_2))
DT$Sub_metering_3<-as.numeric(as.character(DT$Sub_metering_3))
with(DT, plot(x, DT$Sub_metering_1, type = "n", ylab = "Energy sub metering",xlab = ""), plot(x, DT$Sub_metering_2, type = "n", ylab = "Energy sub metering",xlab = ""), plot(x, DT$Sub_metering_3, type = "n", ylab = "Energy sub metering",xlab = ""))
lines(x, DT$Sub_metering_1,col="black")
lines(x, DT$Sub_metering_2,col="green")
lines(x, DT$Sub_metering_3,col="blue")
legend("topright", legend = c("Sub metering 1", "Sub metering 2", "Sub metering 3"), col=c("black","green","blue"), lty=1,cex=0.50)
dev.copy(png, "Plot3.png")
dev.off()